title: "mmlabc-to-smf-rust"
description: "mmlabc-to-smf-rust"
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/cat2151/mmlabc-to-smf-rust
plugins:
  - jekyll-sitemap
