title: "mmlabc-to-smf-rust"
description: "Music Macro Language to Standard MIDI File converter"
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/cat2151/mmlabc-to-smf-rust
